version: '3.7'
services:
  db:
    image: mariadb:10.5.1-bionic
    container_name: mysql
    ports:
    - "3306:3306"
    networks:
      maraidb:
#    volumes:
#      - ./.data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
  php:
    build:
      context: .
      dockerfile: ./DockerfilePHP
    image: php:7.2-fpm-mysqli
    container_name: php
    restart: always
    volumes:
    - ${PWD}/src:/var/www/html/public
#    - "./php.ini:/usr/local/etc/php/conf.d/custom.ini"
    networks:
      maraidb:
  caddy:
    build:
      context: .
      dockerfile: ./DockerfileCaddy
    image: wp-caddy:1.0.4
    container_name: caddy
    restart: always
    ports:
    - 80:80
    - 443:443
    networks:
      maraidb:
    extra_hosts:
      - "www.example2.com:127.0.0.1"
    volumes:
    - ${PWD}/caddy.conf:/etc/caddy/caddy.conf
    - ${PWD}/src:/var/www/html/public
#volumes:
#  wordpress:
#  db:
networks:
  maraidb: